"""Versioned word lists used by the deterministic diagnostics.

These lists describe *context*. They never contribute to the public score.
Bump ``WORDLIST_VERSION`` whenever an entry changes so stored diagnostics
remain interpretable.
"""

from __future__ import annotations

WORDLIST_VERSION = "2026.08.1"

#: Discourse markers common in expository prose. Density is reported as
#: neutral context, not as evidence of authorship.
TRANSITION_PHRASES: frozenset[str] = frozenset(
    {
        "additionally",
        "afterward",
        "also",
        "alternatively",
        "although",
        "as a result",
        "besides",
        "by contrast",
        "consequently",
        "conversely",
        "crucially",
        "despite this",
        "even so",
        "finally",
        "first",
        "firstly",
        "for example",
        "for instance",
        "furthermore",
        "hence",
        "however",
        "importantly",
        "in addition",
        "in conclusion",
        "in contrast",
        "in essence",
        "in fact",
        "in other words",
        "in particular",
        "in short",
        "in summary",
        "indeed",
        "instead",
        "leveraging",
        "likewise",
        "meanwhile",
        "moreover",
        "namely",
        "nevertheless",
        "nonetheless",
        "notably",
        "on the contrary",
        "on the other hand",
        "overall",
        "particularly",
        "second",
        "secondly",
        "similarly",
        "specifically",
        "subsequently",
        "that said",
        "therefore",
        "third",
        "thirdly",
        "thus",
        "to summarize",
        "ultimately",
        "what is more",
        "whereas",
        "while",
    }
)

#: Closed-class words. Their distribution is a classic stylometric feature.
FUNCTION_WORDS: frozenset[str] = frozenset(
    {
        "a",
        "about",
        "above",
        "after",
        "again",
        "against",
        "all",
        "am",
        "an",
        "and",
        "any",
        "are",
        "as",
        "at",
        "be",
        "because",
        "been",
        "before",
        "being",
        "below",
        "between",
        "both",
        "but",
        "by",
        "can",
        "did",
        "do",
        "does",
        "doing",
        "down",
        "during",
        "each",
        "few",
        "for",
        "from",
        "further",
        "had",
        "has",
        "have",
        "having",
        "he",
        "her",
        "here",
        "hers",
        "herself",
        "him",
        "himself",
        "his",
        "how",
        "i",
        "if",
        "in",
        "into",
        "is",
        "it",
        "its",
        "itself",
        "just",
        "me",
        "more",
        "most",
        "my",
        "myself",
        "no",
        "nor",
        "not",
        "now",
        "of",
        "off",
        "on",
        "once",
        "only",
        "or",
        "other",
        "our",
        "ours",
        "ourselves",
        "out",
        "over",
        "own",
        "same",
        "she",
        "should",
        "so",
        "some",
        "such",
        "than",
        "that",
        "the",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "there",
        "these",
        "they",
        "this",
        "those",
        "through",
        "to",
        "too",
        "under",
        "until",
        "up",
        "very",
        "was",
        "we",
        "were",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "whom",
        "why",
        "will",
        "with",
        "would",
        "you",
        "your",
        "yours",
        "yourself",
        "yourselves",
    }
)
