#!/usr/bin/env bash
# Generate production secrets into an env file.
#
#   ./scripts/generate-secrets.sh                  # writes .env.production
#   ./scripts/generate-secrets.sh path/to/file     # writes elsewhere
#
# Refuses to overwrite an existing file: regenerating the encryption key would
# make every already-stored submission undecryptable.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${1:-$ROOT/.env.production}"

if [ -e "$TARGET" ]; then
  echo "Refusing to overwrite $TARGET." >&2
  echo >&2
  echo "It already holds secrets. Regenerating ORIGINLENS_ENCRYPTION_KEY would make" >&2
  echo "every retained submission undecryptable — see docs/PRIVACY_AND_RETENTION.md." >&2
  echo "Delete the file deliberately if that is what you intend." >&2
  exit 1
fi

command -v python3 >/dev/null || { echo "python3 is required" >&2; exit 1; }

python3 - "$TARGET" <<'PY'
import base64, os, pathlib, secrets, sys

target = pathlib.Path(sys.argv[1])

template = f"""# OriginLens production configuration.
#
# Generated by scripts/generate-secrets.sh. The three secrets below are unique
# to this deployment. Keep this file out of version control and back up
# ORIGINLENS_ENCRYPTION_KEY separately — losing it makes every retained
# submission unrecoverable.

# --- Secrets (generated) -----------------------------------------------------
ORIGINLENS_SECRET_KEY={secrets.token_urlsafe(48)}
ORIGINLENS_ENCRYPTION_KEY={base64.urlsafe_b64encode(os.urandom(32)).decode()}
ORIGINLENS_RATE_LIMIT_PEPPER={secrets.token_urlsafe(48)}

# --- Database (generated password) -------------------------------------------
POSTGRES_USER=originlens
POSTGRES_PASSWORD={secrets.token_urlsafe(32)}
POSTGRES_DB=originlens

# --- Your deployment (EDIT THESE) --------------------------------------------
# The public hostname and origin. `localhost` is refused in production.
ORIGINLENS_ALLOWED_HOSTS=originlens.example.com
ORIGINLENS_CORS_ORIGINS=https://originlens.example.com

# The detector. `fake` is refused in production.
ORIGINLENS_DETECTOR_BACKEND=modernbert
ORIGINLENS_MODEL_ID=answerdotai/ModernBERT-base
# Pin a commit SHA: a tag can be moved by the publisher after you review it.
ORIGINLENS_MODEL_REVISION=
ORIGINLENS_MODEL_DEVICE=auto

# Transactional email.
ORIGINLENS_SMTP_HOST=smtp.example.com
ORIGINLENS_SMTP_PORT=587
ORIGINLENS_SMTP_USERNAME=
ORIGINLENS_SMTP_PASSWORD=
ORIGINLENS_SMTP_USE_TLS=true
ORIGINLENS_EMAIL_FROM=no-reply@originlens.example.com

# --- Optional ----------------------------------------------------------------
ORIGINLENS_LOG_LEVEL=INFO
# Loopback port the reverse proxy forwards to.
WEB_PORT=3000
"""

target.write_text(template)
target.chmod(0o600)
print(f"Wrote {target} (mode 600)")
PY

echo
echo "Next:"
echo "  1. Edit $TARGET — the values under 'EDIT THESE' are placeholders."
echo "  2. Back up ORIGINLENS_ENCRYPTION_KEY somewhere safe and separate."
echo "  3. Deploy:  ./scripts/deploy.sh"
